[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
authors = ["CRCR"]
edition = "2024"
repository = "https://github.com/crcrworks/manaba"
license = "MIT"

[workspace.dependencies]
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
